# docker-compose.yml
version: '3.0'
services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=listonymous_production
      - POSTGRES_USER=listonymous
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  web:
    build: 
      dockerfile: Dockerfile.rails
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
